### ISSUE TITLE
Support for Subscription Offers

### ISSUE THREAD

**Issue by Vortec4800** [adaptyteam/AdaptySDK-iOS#10]
Will you guys have support for subscription offers? I want to give some users an additional discount, and it looks like offers are the way to do it:

https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_subscription_offers_in_your_app

**Comment by iwitaly** [comment]
Hey @Vortec4800 ✌️
We do support all kind of offers! Including introductory and promotional. Just configure it inside Adapty Dashboard https://app.adapty.io/products and here's a doc https://docs.adapty.io/purchase-infrastructure/product#subscription-offers

**Comment by Vortec4800** [comment]
Thank you, when I first saw that in the dashboard I thought it was just for push campaigns.

The documentation was helpful in getting the offer added, but is there a document that shows how to actually use it? I see discounts on product models, but how do I make the purchase with a discount?

**Comment by iwitaly** [comment]
Yeap! Just take a look at https://github.com/adaptyteam/AdaptySDK-iOS/blob/master/Documentation/AdvancedUsage.md#making-purchases 

The app received ProductModel from our servers and then you call `makePurchase` with the appropriate subscription offer. Also, keep in mind that only promotional offers are optional (so you control it for each user), introductory offers such as free trials are not controllable and available for all users and you manage them in AppStore Connect.

**Comment by Vortec4800** [comment]
Okay thank you, I see now.

**Comment by phucnd0604** [comment]
i have an error with applicationUsername, as the Apple doc: 
You must set applicationUsername to be the same as the one used to generate the signature
so my purchase with offer always fail.
Any one can help?

**Comment by ClutchpointsLinks** [comment]
Hey, SDK has build-in support for promo offers, no additional logic related to `applicationUsername` required.
https://docs.adapty.io/docs/ios-making-purchases

**Comment by AKyashkin** [comment]
> i have an error with applicationUsername, as the Apple doc: You must set applicationUsername to be the same as the one used to generate the signature so my purchase with offer always fail. Any one can help?

Hey, SDK has build-in support for promo offers, no additional logic related to `applicationUsername` required.
https://docs.adapty.io/docs/ios-making-purchases

**Comment by phucnd0604** [comment]
> 

yes the SDK is not require applicationUsername but StoreKit is required
```swift
// An example function that makes a buy request with a promotional offer attached.
public func buyProduct(productIdentifier: SKProduct, forUser usernameHash: String, withOffer discountOffer: SKPaymentDiscount) {

    // The original product being purchased.
    let payment = SKMutablePayment(product: product)

    // You must set applicationUsername to be the same as the one used to generate the signature.
    payment.applicationUsername = usernameHash

    // Add the offer to the payment.
    payment.paymentDiscount = discountOffer

    // Add the payment to the queue for purchase.
    SKPaymentQueue.default().add(payment)
}
```

**Comment by AKyashkin** [comment]
It is a nullable property and can be left either empty or filled with an empty string.
https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername

Promo offers work properly in terms of the SDK, make sure you've configured everything properly https://docs.adapty.io/docs/app-store-promotional-offers

**Comment by phucnd0604** [comment]
> It is a nullable property and can be left either as nil or filled with an empty string. https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername
> 
> Promo offers work properly in terms of the SDK, make sure you've configured everything properly https://docs.adapty.io/docs/app-store-promotional-offers

i have configure the SDK with p8 file, i can buy without offer but get error with offerID, does the SDKwork with sandbox?

**Comment by ikondrakov** [comment]
> > It is a nullable property and can be left either as nil or filled with an empty string. https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername
> > Promo offers work properly in terms of the SDK, make sure you've configured everything properly https://docs.adapty.io/docs/app-store-promotional-offers
> 
> i have configured the SDK with p8 file, i can buy without offer but get error with offerID, does the SDKwork with sandbox?

Hey! I assume we've had a conversation over this issue earlier today. My advice here would be to check out if you set the Subscription Key ID on the iOS SDK settings page:
﻿
﻿https://app.adapty.io/settings/ios-sdk
