### ISSUE TITLE
Upadte from AdaptyUI 3.2.0 to 3.2.2

### ISSUE THREAD

**Issue by parthDev123** [adaptyteam/AdaptySDK-iOS#100]
We used Adapty 3.2.0 before the upgrade, and everything worked fine. However, I now receive these errors:

xcode version: Version 15.4 
macOS: 14.5

pod 'Adapty', '3.2.2'
pod 'AdaptyUI', '3.2.2'

![Screenshot 2024-12-17 at 5 57 04 PM](https://github.com/user-attachments/assets/9f543186-a498-4fe7-8082-5c3540847e08)

**Comment by x401om** [comment]
I will close the issue. Please feel free to reopen it if you believe the problem persists.
