### ISSUE TITLE
Duplicate profiles when setting Customer User ID in v3.2

### ISSUE THREAD

**Issue by alexflm** [adaptyteam/AdaptySDK-iOS#101]
After migrating from version 3.0.3 to version 3.2.2 of Adapty SDK, a user identification issue was discovered. When SDK is initialized without Customer User ID and the identifier is passed later with a separate call, Adapty analytics creates duplicate records:
- First profile and install without Customer User ID
- Second profile and install with Customer User ID

The only way to avoid duplication is to initialize SDK only after user authentication when Customer User ID is already available.​​​​​​​​​​​​​​​​

**Adapty SDK**

3.2.2

**Xcode Version**

16.2

**Installation Method**

Swift Package Manager

**Targeted Platforms**

iOS

**Comment by x401om** [comment]
Hi @alexflm, thank you for the report, we're looking into it

**Comment by x401om** [comment]
@alexflm should be fixed in [3.2.4](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/3.2.4)

**Comment by x401om** [comment]
I will close the issue. Please feel free to reopen it if you believe the problem persists.
