### ISSUE TITLE
Callbacks called twice

### ISSUE THREAD

**Issue by MaximKotliar** [adaptyteam/AdaptySDK-iOS#11]
Hi, I've noticed that all callbacks in you SDK called twice with different 'state'. But in some cases it called only once, it makes usage harder in some cases, for ex. DispatchGroups. Maybe I can specify somewhere to call callback only once for state .synced, or specify behaviour like synced if can or cached if not.

**Comment by AKyashkin** [comment]
Hey, 
If you want to sync data in DispatchGroups or similar – i.e. to be sure callback called only once, just check for `state == .synced` in callback.  
We guarantee that callback will be called at least once with `.synced` state, so it should be enough for you.

**Comment by MaximKotliar** [comment]
Hm, I have some cases when it called only once with .cached, I will recheck, thanks!

**Comment by MaximKotliar** [comment]
Ok, it seems to work properly, thanks.
