### ISSUE TITLE
Add forceUpdate to getPurchaserInfo

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#13]

**Comment by AKyashkin** [comment]
We actually always re-sync purchaserInfo on each `getPurchaserInfo` call, but we do it in background and you can always get those updates in AdaptyDelegate method.
But sure, we can add this `forceUpdate` property, which basically will just call user callback after background sync.

**Comment by larryonoff** [comment]
> We actually always re-sync purchaserInfo on each `getPurchaserInfo` call, but we do it in background and you can always get those updates in AdaptyDelegate method.
> But sure, we can add this `forceUpdate` property, which basically will just call user callback after background sync.

Our application requests purchaserInfo immediately after purchase, when Adapty delivers updated purchaser info, a bit later. Generally speaking our logic needs option to use  `getPurchaserInfo` in call pipeline.

**Comment by AKyashkin** [comment]
@larryonoff as soon as we receive successful receipt validation response from backend side, we instantly update local `purchaserInfo` cache, since we have it in response of this receipt validation request.
According to this, `.makePurchase()`callback already contains updated `purchaserInfo`, and this exact info is returning in `.getPurchaserInfo()` method.

**Comment by larryonoff** [comment]
> @larryonoff as soon as we receive successful receipt validation response from backend side, we instantly update local `purchaserInfo` cache, since we have it in response of this receipt validation request.
> According to this, `.makePurchase()`callback already contains updated `purchaserInfo`, as well as `.getPurchaserInfo()` method returns exactly the same data.

Thanks for explanation. I'll check our logic.

**Comment by AKyashkin** [comment]
@larryonoff we also added `forceUpdate` to `getPurchaserInfo` request in latest update 1.11.1.
