### ISSUE TITLE
Please bump CryptoSwift to 1.4.0, if there's no limitations

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#18]

**Comment by AKyashkin** [comment]
Will do that next week.
In general, we'll get rid of this dependency in upcoming month or two.

**Comment by larryonoff** [comment]
@AKyashkin remove dependency is much better :)

**Comment by AKyashkin** [comment]
@larryonoff bumped to the latest 1.4.0 version in SDK v1.13.2
