### ISSUE TITLE
SPM doesn't support two numbers versioning

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#21]
Hello,

Could you please make update in naming of versions.

It looks that SPM doesn't support two number versions, e.g. "1.14", "1.15". So it always should have three numbers, e.g. "1.14.0", "1.15.0".

Please see the errors that I have:

in case of specifying "1.15" 
> The error is pretty simple "Failed to parse the manifest file".

in case of specifying "1.15.0"
> Dependencies could not be resolved because no versions of 'AdaptySDK-iOS' match the requirement 1.15.0..<2.0.0 and root depends on 'AdaptySDK-iOS' 1.15.0..<2.0.0.

Thank you!

**Comment by AKyashkin** [comment]
Thanks for your report.
We already found this issue and will deliver an update today.

**Comment by ihityouback** [comment]
@larryonoff Added new tag 1.15.1 which satisfies the conditions of SPM

**Comment by larryonoff** [comment]
Thanks!
