### ISSUE TITLE
Offline support of Adapty.getPaywalls() for SKTestSession in UITests

### ISSUE THREAD

**Issue by Kondamon** [adaptyteam/AdaptySDK-iOS#22]
Adapty SDK doesn't support SKTestSession in UITests. 

The problem arise because `Adapty.getPaywalls()` doesn't return any `PaywallModel` when you are offline. Also `Adapty.setFallbackPaywalls(paywalls)` doesn't resolve this issue. I doesn't receive any `PaywallModel` when I'm offline after calling `Adapty.getPaywalls()` but an error. As a consequence I can not display any products and not do a successful UITest when I'm offline.

A possible **workaround** would be, if you provide an additional API call `getFallbackPaywallModel()` to get the fallback paywall `PaywallModel`. Then it would be possible to display those received products when I'm offline during UITests.

**Comment by Kondamon** [comment]
@AKyashkin, great to hear. Do you already have a timeframe when offline paywalls are supported?
Thanks for clarifying. Offline receipt validation during UITests can easily be done via TPInAppReceipt, can highly recommend it for tests.

**Comment by AKyashkin** [comment]
@Kondamon hey, we scheduled this release for the end of the next week.

**Comment by AKyashkin** [comment]
@Kondamon hey, 
It's live now, offline support for paywalls is available since 1.16.1 SDK version. Keep in mind, SDK still needs to receive paywalls at least once somehow – through fallback paywalls or regular paywalls request.
