### ISSUE TITLE
Critical IAP Bug

### ISSUE THREAD

**Issue by joshuazmiller** [adaptyteam/AdaptySDK-iOS#24]
There is a critical issue where Adapty is returning no subscriptions for existing and new active subscribers. We are getting lots of emails from customers the past few hours complaining that they paid and the app is still locked. We have not changed or updated our app. We have been using Adapty for about a year. Please look into this ASAP as it's impacting us financially and this is a major concern.

**Comment by ikondrakov** [comment]
Hey Joshua, 

This is Ivan here. I do believe, we've spoken earlier. Our guys looking into this!

**Comment by joshuazmiller** [comment]
This issue was fixed a couple weeks ago. Don't want to leave open. Thank you :)
