### ISSUE TITLE
Support Xcode simulator

### ISSUE THREAD

**Issue by conversun** [adaptyteam/AdaptySDK-iOS#25]
After completing the purchase using the emulator, it prompts an error:

`Error Domain=com.adapty.AdaptySDK Code=400 "Status: APPLE_RECEIPT_VALIDATION_ERROR. Details: 21002" UserInfo={NSLocalizedDescription=Status: APPLE_RECEIPT_VALIDATION_ERROR. Details: 21002}`

**Comment by AKyashkin** [comment]
We've scheduled support for StoreKit local testing for the end of the year.
Right now local receipt validation is not possible.

**Comment by gerchicov-vg** [comment]
@AKyashkin currently local testing works so so. What about to add a possibility to make the receipt validation always successful if an user runs the app in the debug mode?
