### ISSUE TITLE
Support for async/await syntax

### ISSUE THREAD

**Issue by rudrankriyam** [adaptyteam/AdaptySDK-iOS#31]
Any ETA/plan for supporting async/await syntax for iOS 13+/macOS 11+?

**Comment by larryonoff** [comment]
Just added https://github.com/adaptyteam/AdaptySDK-iOS/pull/35

**Comment by rudrankriyam** [comment]
That's great! I will use your fork for now then. I love that you used the `typealias`, especially `PurchaseResult` for readability!

**Comment by larryonoff** [comment]
@rudrankriyam You're welcome. Hope that PR will be merged soon.

I prefer struct to typealias, but I don't want result differs from the original method result.

**Comment by AKyashkin** [comment]
@larryonoff thanks! We'll take a look and try to schedule a release for a next week.

**Comment by rudrankriyam** [comment]
Awesome! I can happily close this issue.
