### ISSUE TITLE
Cannot Mock PaywallModel

### ISSUE THREAD

**Issue by GutteApps** [adaptyteam/AdaptySDK-iOS#36]
Hi, 

I'm trying to mock PaywallModel so I can test the creation of Paywalls before submitting my IAP for review. 

I looked at ModelsTest in the example project and created this similiar function:

```
    func getMockPaywall() -> PaywallModel?{
        
        guard let url = Bundle.main.url(forResource: "Paywall", withExtension: "json") else {
            print("Missing file: Paywall.json")
            return nil
        }
        do{
            let data = try Data(contentsOf: url)
            let json = try JSONSerialization.jsonObject(with: data, options: []) as! [String: Any]
            let paywall = try PaywallModel(json: attributes(from: json))

            return paywall
        }
        catch{
            return nil
        }
        
        return nil
     
    }
     private func attributes(from params: Parameters) -> Parameters {
        return ["attributes": params]
    }
```

For some reason, the compiler seems to think I'm using the wrong initializer. 
I thought this was a conflict specific to my project but the same error appears when I create a clean project with only Adapty. 
<img width="724" alt="Screen Shot 2022-05-03 at 6 28 30 PM" src="https://user-images.githubusercontent.com/4751301/166484738-6382f808-1c49-44e5-ada1-9318e44930de.png">

I'm using version 1.17.0, Installed with SPM, on SwiftUI if that makes a difference. 

Please help 🙏

**Comment by rudrankriyam** [comment]
From what I understand, if you look at the declaration of `PaywallModel`, you will see the `required init?(json: Parameters)` is not **public**; hence the compiler cannot access it. 

I forked the repository and made the init public: 

```
public required init?(json: Parameters) throws {
}
```

And it works fine. Although, the library authors can tell better if they want to expose the initializer of `PaywallModel` or not.

**Comment by GutteApps** [comment]
mmm.. the class itself is public. I didn't realize the initializer needs to be explicitly public as well. thanks
