### ISSUE TITLE
Example does not work properly

### ISSUE THREAD

**Issue by fhefh2015** [adaptyteam/AdaptySDK-iOS#39]
ld: in /Pods/AppsFlyerFramework/iOS/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerHTTPClient.o), building for iOS /Simulator, but linking in object file built for iOS, file '/Pods/AppsFlyerFramework/iOS/AppsFlyerLib.framework/AppsFlyerLib' for architecture arm64

Mac mini (M1, 2020)

**Comment by rudrankriyam** [comment]
This [PR](https://github.com/adaptyteam/AdaptySDK-iOS/pull/38) which is merged now, should solve it!
