### ISSUE TITLE
setFallbackPaywalls returns error

### ISSUE THREAD

**Issue by MatusevichMaxim** [adaptyteam/AdaptySDK-iOS#44]
Hi Adapty Team!
I'm trying to use fallback feature with offline. I loaded fallback-json from dashboard and then added it into a project. 
Afterwards i try set fallback from file: 
```
private func fetchFallback() {
        let file = R.file.fallback_paywallsJson
        if let path = Bundle.main.path(forResource: file.name, ofType: file.pathExtension),
           let paywall = try? String(contentsOfFile: path, encoding: .utf8) {
            Adapty.setFallbackPaywalls(paywall, completion: { error in
                if let error = error {
                    Log.error(error)
                }
            })
        }
    }
```

In completion block i get an error "An unknown error occurred".

**Comment by x401om** [comment]
Hi, @MatusevichMaxim! Are you still facing this issue? If yes, could you please provide us some more information about the error, is there an `originalError` property filled? What is `adaptyErrorCode` value?

**Comment by MatusevichMaxim** [comment]
Yes, it's still happening. Look at the error:
<img width="483" alt="Screenshot 2022-07-25 at 22 56 21" src="https://user-images.githubusercontent.com/18659201/180853476-90ed27b6-f5da-4032-ab4b-7f1ca86a625e.png">

**Comment by x401om** [comment]
The problem was that even though fallback_paywalls were handled correctly, the callback could get an error from StoreKit. It didn't affect the operation of the method. We recently released a public beta where we fixed this problem, now you won't get this kind of error. All fixes will be available in the stable release soon.
