### ISSUE TITLE
Main Thread Checker fails on Adapty.getPaywalls call from other that main thread

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#5]
There's functions call-chain:
`Adapty.getPaywalls` -> `IAPManager.getPaywalls` -> `IAPManager.getPaywallsAndSyncProducts`.

`IAPManager.getPaywallsAndSyncProducts` uses `UIApplication` under the hood. As result `Adapty.getPaywalls` call from other that main thread fails Main Thread Checker.

Expected behaviour: Adapty.getPaywalls can be called from any thread.

**Comment by AKyashkin** [comment]
@larryonoff hey, thanks for your feedback.

Fixed in https://github.com/adaptyteam/AdaptySDK-iOS/commit/fcfc5877d0e9752555a6e3e9d92f65a0da9e6be3
Will go live in the next couple of days.

**Comment by larryonoff** [comment]
@AKyashkin thanks! The fix looks perfect.

**Comment by Skifcha** [comment]
@larryonoff it's live now, available in 1.7.0
