### ISSUE TITLE
PurchaserInfo not updated when internet connection is not available

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#55]
Our application replies on Adapty purchaser info by using `AdaptyDelegate.didReceiveUpdatedPurchaserInfo`. Adapty requests PurchaserInfo from backed in `Adapty.activate` method. But `didReceiveUpdatedPurchaserInfo` not reported when internet connection is not available.

There's an option to get PurchaserInfo, i.e. `Adapty.getPurchaserInfo(forceUpdate:)`. So the there's a flow:
1. call `Adapty.activate`
2. call `Adapty.getPurchaserInfo(forceUpdate: false)`

this entails possible two requests to simultaneous requests to backed when internet is available. What is not optimal.

So I propose two options.
1. Call `AdaptyDelegate.didReceiveUpdatedPurchaserInfo` in `private func configure(_ completion: ErrorCompletion? = nil)` when purchaserInfo is not empty, before identify or getPurchaserInfo calls. #54
2. Add `Adapty.getPurchaserInfo(forceUpdate:)` option to skip network request.

Thanks!

**Comment by x401om** [comment]
Hey, @larryonoff ! We have released the new version of our SDK, check it out!

[Here is](https://docs.adapty.io/docs/ios-subscription-status#listening-for-subscription-status-updates) the part of our docs about this thing.
