### ISSUE TITLE
Example code is old version

### ISSUE THREAD

**Issue by dursundogan35** [adaptyteam/AdaptySDK-iOS#57]
Hi,

This version has sample with version 1.17.7. But your stable version is 2.0.0. Can you share the sample code for the new version?

**Comment by x401om** [comment]
Hey, the UIKit example contains up to date code. We will update the SwiftUI one soon.

**Comment by dursundogan35** [comment]
I'm looking forward to the swift version. Thanks for answer

**Comment by hopye** [comment]
Yes. Code is giving a series of problems. for ex there's no getPaywalls() func. I don't know how to get the paywalls lol

**Comment by x401om** [comment]
@hopye the new SDK doesn't contain the `getPaywalls()` method. You should use a [`getPaywall(_:_:)`](https://swift.adapty.io/documentation/adapty/adapty/getpaywall(_:_:)).
Also you can check our Example [here](https://github.com/adaptyteam/AdaptySDK-iOS/blob/master/Examples/UIKit/Adapty/PurchasesObserver.swift).

**Comment by dursundogan35** [comment]
Hi,

Can you provide a release date for the swiftui sample code? All examples were made with the previous version. I'm stuck

**Comment by x401om** [comment]
@dursundogan35 The functionality of our SDK does not depend on the framework you use to create your UI. Moreover, in many parts of UIKit Example we use SwiftUI. 
We expect that the Example in the [SwiftUI folder](https://github.com/adaptyteam/AdaptySDK-iOS/tree/master/Examples/SwiftUI) will be updated in January. Example in the [UIKit folder](https://github.com/adaptyteam/AdaptySDK-iOS/tree/master/Examples/UIKit) always works with the current version of the SDK, as the dependency is local.
I also recommend you to check out our [documentation](https://docs.adapty.io/docs/) as it contains lots of code snippets.

**Comment by dursundogan35** [comment]
Hi,
Yes, the functionality of your SDK does not depend on the framework. Agreed.  There is something I don't understand. So why is your stable version set to 2.x.x? If you publish this, there should have been an example too. Models are different, functions are different and  if you withdraw your support for the 1.x.x version, I have to do this integration again. I don't want to take this risk. Maybe I should look into other solutions.

**Comment by x401om** [comment]
@dursundogan35 we have updated the [SwiftUI Example App](https://github.com/adaptyteam/AdaptySDK-iOS/tree/master/Examples/SwiftUI).
