### ISSUE TITLE
Fixed Code. finally working, please update 

### ISSUE THREAD

**Issue by hopye** [adaptyteam/AdaptySDK-iOS#60]
In the PaywallService.

var paywallViewModel: PaywallViewModel?

MARK AS @Published !!!

@Published var paywallViewModel: PaywallViewModel?

Otherwise the PaywallView won't see the change and access the var in the View  :).

Best Regards!

**Comment by x401om** [comment]
@hopye [fixed! ](https://github.com/adaptyteam/AdaptySDK-iOS/commit/593a0381de243543e44858446fb96161af7ae8c9)
