### ISSUE TITLE
Please remove 'dummy' profiles

### ISSUE THREAD

**Issue by aritroper** [adaptyteam/AdaptySDK-iOS#62]
I am frustrated that dummy profiles are created when users anonymously log in to the app. I have tried to circumvent this by only calling Adapty.activate() during the login process, but it would be great if these dummy profiles were hidden from the dashboard, or there were a way to remove them all together.

**Comment by x401om** [comment]
Hey, @aritroper! 

Anonymous user profiles are indeed created, but they do not affect analytics in any way. The users section is almost never used for evaluating metrics, but only for selective analysis of specific users by their id.
If you have any questions related to the dashboard functionality, I recommend that you contact the technical support team via email or Intercom.
