### ISSUE TITLE
Plan for removal of deprecated iAd framework from Adapty SDK

### ISSUE THREAD

**Issue by ksemianov** [adaptyteam/AdaptySDK-iOS#67]
Hello Adapty Team,

I wanted to bring to your attention that the [iAd framework](https://developer.apple.com/documentation/iad) has been officially deprecated by Apple. Furthermore, I recently received a communication from Apple indicating that the iAd framework will be completely removed from iOS within the next 2 years. Post-removal, any applications still utilizing iAd will experience crashes.

Given the critical nature of this update and to ensure a smooth user experience for applications leveraging the Adapty SDK, could you please share any plans or timelines regarding the removal of iAd usage within the SDK?

Thank you for your attention to this matter, and I look forward to your response.

**Comment by x401om** [comment]
Hey, @ksemianov! Thank you for noticing that. We have plans to update our SDKs and get rid of the iAd framework by the end of this year. I will keep this issue open.

**Comment by x401om** [comment]
@ksemianov Hi, we have removed iAd usage in the [latest release](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/2.8.0).

**Comment by astrokin** [comment]
@x401om it's look like `iAd` is still there https://github.com/CocoaPods/Specs/blob/master/Specs/a/1/b/Adapty/2.10.2/Adapty.podspec.json#L37
