### ISSUE TITLE
Missing Objective-C Interop

### ISSUE THREAD

**Issue by pnametala** [adaptyteam/AdaptySDK-iOS#68]
Hey all,

Currently trying to use Adapty on a Kotlin Multiplatform project.

As the library is purely Swift, it's code can't be accessed via iosMain on a KMP project.

One solution is to create an obj-c interop to facilitate that.

Would be awesome to have it as standard in this library

**Comment by x401om** [comment]
Hi, @pnametala. We don't have Objective C wrapper support in our roadmap since it is a legacy technology. If you are planning to use obj-c in your projects I would recommend you to wrap only necessary APIs by yourself.

**Comment by arok** [comment]
is someone will face the same issue, here is the start point to integrate Swift library to KMP project https://medium.com/kodein-koders/create-a-kotlin-multiplatform-library-with-swift-1a818b2dc1b0
