### ISSUE TITLE
Crash on Adapty.SDK.SendEvents Thread

### ISSUE THREAD

**Issue by dongdong945** [adaptyteam/AdaptySDK-iOS#69]
Operating System: iOS 16.0.0
Device: iPhone 14 Pro
SDK Version: Adapty 2.6.2

Crashed: Adapty.SDK.SendEvents
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

```
Crashed: Adapty.SDK.SendEvents
0  libswiftCore.dylib             0x41645c swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::incrementSlow(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 60
1  libswiftCore.dylib             0x3d8f00 swift_retain + 124
2  libswiftCore.dylib             0x3d8f00 swift_retain + 124
3  libswiftCore.dylib             0x41eadc swift_bridgeObjectRetain + 52
4  Adapty                         0x7db9c closure #1 in EventsManager.trackEvent(_:completion:) + 68 (EventsManager.swift:68)
5  Adapty                         0x11e0c thunk for @escaping @callee_guaranteed @Sendable () -> () + 28 (<compiler-generated>:28)
6  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
8  libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
9  libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
10 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
11 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xb98 start_wqthread + 8
```

This crash occurred online, albeit only one. Hope the above information can help

**Comment by x401om** [comment]
Hi, @dongdong945, thank you, we will investigate the issue.

**Comment by x401om** [comment]
Could you please explain whether you are using the Adapty.logShowPaywall or Adapty.logShowOnboarding methods? Also, are you passing any completion handlers into them? If yes, could you provide the relevant code snippets for us?

**Comment by dongdong945** [comment]
I didn't call Adapty.logShowOnboarding, only Adapty.logShowPaywall.

When calling Adapty.logShowPaywall, I called Adapty.getPaywall(paywallId, locale: local) again to get the Paywall, and then called Adapty.logShowPaywall(paywall, nil). **This paywall is not the same object as the paywall used for display.** Is there something wrong here?
