### ISSUE TITLE
didReceiveUpdatedPurchaserInfo notifies that subscription is not active when it's active

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#7]
`didReceiveUpdatedPurchaserInfo` sends two notifications on app initialization:
- first - that standard subscription is NOT active
- then second, almost immediately - that standard subscription is active

**expected behavior**: one event that subscription is active when it's active

**Comment by Skifcha** [comment]
@larryonoff hey, did you check "state" property in method callback?
Callback calls two times – first with "state"=.cached, which delivers previously cached value; the second one is with "state"=.synced, which means data fully synced from server.
If your data is sensitive and needs to be synced all the time, just look at the "state"=.synced and it should be enough.

**Comment by larryonoff** [comment]
> @larryonoff hey, did you check "state" property in method callback?
> Callback calls two times – first with "state"=.cached, which delivers previously cached value; the second one is with "state"=.synced, which means data fully synced from server.
> If your data is sensitive and needs to be synced all the time, just look at the "state"=.synced and it should be enough.

Thanks for the reply. I don't see that `PurchaserInfoModel` or `didReceiveUpdatedPurchaserInfo` have state.

**Comment by Skifcha** [comment]
@larryonoff ok, got it. I have several questions to clarify things:
1. Does this happen only at the very first session, or at every session?
2. Does your user have any purchased products?
3. Can you also [enable logs](https://github.com/adaptyteam/AdaptySDK-iOS/#debugging) and send them to us for the session your issue appears? Just set `Adapty.logLevel = .verbose` before your `Adapty.activate()` call.

**Comment by larryonoff** [comment]
@Skifcha I just tried steps to reproduce for Adapty version 1.7.0, as result everything works fine.

FYI. Steps to reproduce:
1. Purchase any subscription.
2. Wait till subscription renews.
3. Restart debugger

**Comment by AKyashkin** [comment]
@larryonoff so, back to the issue. It's fine within 1.7.0+ version of the SDK, right?

**Comment by larryonoff** [comment]
@AKyashkin 1.7.* works good for me. Closing the issue
