### ISSUE TITLE
Infinite error on MacOS - ERROR: #API# ERROR

### ISSUE THREAD

**Issue by vitya87ua** [adaptyteam/AdaptySDK-iOS#75]
**Infinite error on MacOS**
I have tried on 2.5.1, 2.6.4 & 2.9.4 always the same
![2024-02-09 12 49 59](https://github.com/adaptyteam/AdaptySDK-iOS/assets/12259627/803828db-2c71-468e-b813-1f8d885cbf25)

**Comment by x401om** [comment]
Hi, @vitya87ua, thank you for the issue, we are investigating it, I will come back to you soon.

**Comment by x401om** [comment]
@vitya87ua we're observing some unusual values from you device, could you please share which device model are you using?

**Comment by vitya87ua** [comment]
> @vitya87ua we're observing some unusual values from you device, could you please share which device model are you using?

MacBook Air M2 2022, Sonoma 14.1.1

**Comment by x401om** [comment]
Hi @vitya87ua, we have changed the way how we work with the device name in [2.9.5](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/2.9.5), could you please try this version?

**Comment by vitya87ua** [comment]
Hi @x401om the error is gone)
