### ISSUE TITLE
OneSignal Integration is broken

### ISSUE THREAD

**Issue by alexkulaga** [adaptyteam/AdaptySDK-iOS#76]
This code does not save oneSignalSubscriptionId property, even though a property "one_signal_subscription_id" is sent to the server according to Debug logs. 
Adapty SDK version 2.9.4

```
let builder = AdaptyProfileParameters.Builder()
                        .with(amplitudeDeviceId: amplitudeID)
                        .with(mixpanelUserId: mixpanelID)
                        .with(oneSignalSubscriptionId: "test_subscription_id")
                        .with(pushwooshHWID: "test_push_woosh")
                        .with(oneSignalPlayerId: "test_player_id")

try await Adapty.updateProfile(params: builder.build())
```

<img width="371" alt="Screenshot 2024-02-12 at 1 26 57 PM" src="https://github.com/adaptyteam/AdaptySDK-iOS/assets/35011859/0b131374-acbd-4a34-a101-ff4a32b96319">

The issue leads to the integration is not working

**Comment by x401om** [comment]
Hello, @alexkulaga, thank you for reaching out! As far as I can see, you have already contacted our technical support. Since your question is not directly related to the functionality of our SDK, I'll have to close this issue.
