### ISSUE TITLE
Crash on SKQueueManager.receivedFailedTransaction

### ISSUE THREAD

**Issue by AlexSaraev** [adaptyteam/AdaptySDK-iOS#84]
Operating System: iOS 17.4.1
Device: Phone 12 Pro Max
SDK Version: Adapty 2.10.3

Fatal Exception: NSRangeException
*** -[__NSArrayM removeObjectsInRange:]: range {0, 1} extends beyond bounds for empty array

`SK1QueueManager+MakePurchase.swift - Line 40
closure #1 in SK1QueueManager.receivedFailedTransaction(_:) + 40`

This crash affected users of App Store. But we don't observe and don't finish the transactions, in contrast to the previous justification. All we do is use Adapty throughout the entire purchasing process.

_Originally posted by @AlexSaraev in https://github.com/adaptyteam/AdaptySDK-iOS/issues/77#issuecomment-2095849950_

**Comment by x401om** [comment]
Hi, @AlexSaraev! Could you please share the full stacktrace of this crash so we could analyze it deeper? For now it looks like you have encountered the same iOS bug as described in #77.

**Comment by x401om** [comment]
Hi! We’ve released a [new version](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/3.2.0) that relies on the new StoreKit2 API. I hope this will help reduce the number of SK1 crashes, as the iOS version you reported now supports SK2. If you have any updates regarding the crash on SK1, please don’t hesitate to reopen the issue.
