### ISSUE TITLE
Add support for StoreKit local testing introduced in Xcode 12 / iOS 14

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#9]

**Comment by AKyashkin** [comment]
@larryonoff the only thing which is not working with StoreKit local testing is receipt validation (and related dashboard data, of course, since we can't read receipt).
Are you talking about this exact thing or it's something else?

**Comment by AKyashkin** [comment]
@larryonoff one quick thing we can do is to not validate receipts at all, in case it was a StoreKit local testing transaction.

**Comment by AKyashkin** [comment]
@larryonoff any update here or should we close the issue?
