### ISSUE TITLE
hasViewConfiguration parameter is not returned Swift

### ISSUE THREAD

**Issue by Silverviql** [adaptyteam/AdaptySDK-iOS#93]
https://adapty.io/docs/get-pb-paywalls

According to your documentation, to find out that you can display the paywall builder, and not a manually written paywall, there is an additional parameter hasViewConfiguration, now it is not returned

sdk version 3.1.0

<img width="1005" alt="a3548b9ea8436d9c80b8f4ffc304d7a0b1acc5b7" src="https://github.com/user-attachments/assets/e8d0d29e-1665-41a9-a161-41fbeaf3d115">

**Comment by x401om** [comment]
Hi @Silverviql, what do you mean by "it is not returned" ?

**Comment by Silverviql** [comment]
hi @x401om 
if you look at the screenshot, you will see in the debugger that the paywall object did not return the hasViewConfiguration parameter although the viewConfiguration parameter is not empty

**Comment by x401om** [comment]
@Silverviql `hasViewConfiguration` is a computed property and is not expected to appear in the variables pane. It is implemented as `public var hasViewConfiguration: Bool { viewConfiguration != nil }`, so you should get `true` as the result here.
