### ISSUE TITLE
Adapty v2 to v3.2 migrate not show product price error

### ISSUE THREAD

**Issue by UtkuGlsvn** [adaptyteam/AdaptySDK-iOS#95]
#tEkNy5# event_didPartiallyLoadProducts: ["cosmic_annual_BF_2024"]
v3.2.0, AdaptyUI/AdaptyEventsHandler.swift#102

**Comment by UtkuGlsvn** [comment]
We have solved this problem now, but after switching from Adapty v2 to v3, even if the purchase is successful, it is not reflected in Adapty. Do we need to change anything?

**Comment by x401om** [comment]
@UtkuGlsvn There is a known issue in the Sandbox environment where iOS does not properly handle subscription cycle renewals after a previous subscription was canceled. We are working on a workaround, which will hopefully be released later this week.

**Comment by x401om** [comment]
Hi @UtkuGlsvn, please update to [3.3.0](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/3.3.0), I hope this behaviour is fixed now.
