### ISSUE TITLE
Xcode Cloud build failed: "Cannot find 'onGeometryChange' in scope"

### ISSUE THREAD

**Issue by Sun-Woo-Kim** [adaptyteam/AdaptySDK-iOS#97]
I faced the following issue: This issue occurred in xcode cloud, and I am using the latest version of Adapty.
![Screenshot 2024-12-12 at 6 30 47 PM](https://github.com/user-attachments/assets/bf40f84b-b6cc-429d-86ae-1e4115d833f6)

**Comment by x401om** [comment]
Hi @Sun-Woo-Kim, do you have any issues building the app locally?

**Comment by x401om** [comment]
I believe the reason is because Xcode Cloud uses Xcode 16.2, we also have an issue for it (#99)

**Comment by x401om** [comment]
@Sun-Woo-Kim please update to [3.2.2](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/3.2.2). 

As I understand, you can also specify any Xcode version when setting up the Xcode Cloud workflow.

**Comment by Sun-Woo-Kim** [comment]
Hello @x401om  , thanks to your prompt and helpful update, I was able to resolve the issue. After updating to `3.2.2` , I confirmed that the build updates correctly. Thank you.
