### ISSUE TITLE
AdaptyUI does not compile on the latest version of Xcode

### ISSUE THREAD

**Issue by mattisssa** [adaptyteam/AdaptySDK-iOS#99]
![CleanShot 2024-12-12 at 12 59 28](https://github.com/user-attachments/assets/aefa6700-5efd-4b83-9231-89f1d5599890)

XCode: Version 16.2 (16C5032a)
macOS: 15.1.1 (24B91)
Machine: Apple M1 Max, 64 GB

**Comment by x401om** [comment]
Hi @mattisssa! Thank you for the issue, we will take a look

**Comment by x401om** [comment]
@mattisssa please update the dependency to [3.2.2](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/3.2.2)

**Comment by mattisssa** [comment]
Everything works fine 🙌
Sorry for the late response, couldn't try earlier 😁
